examples/boltzmann_wealth_model/Readme.md
examples/boltzmann_wealth_model/requirements.txt

Update outdated readme to be more accurate + clean up requirements.txt of unnecessary dependencies.
Script runs succesfully and I could see the simulation on my browser (pretty cool!).
One question: there is current a discrepancy between the jupyter notebook and the code in model.py. Notably the `self.datacollector.collect(self)` happens both within the init and in the step function in `model.py`, and the order is also switched within `step` (does it matter when the data collector collects data? would it miss the last step in the jupyter notebook?)
Excited for my first PR/contribution!

Update outdated readme for Boltmann example + trim requirements.txt

---

.pre-commit-config.yaml
examples/caching_and_replay/run.py

Pathlib is a new(-ish) standard library module (introduced 3.4) that provides a cleaner and more reliable way to handle file paths than the old os.path methods. They bake in OS-safety, adapting to Windows back-slashes and Unix forward-slashes seamlessly. Switching to Pathlib cleans up the code a little and avoids possible Windows problems.
Code by Phil Robare (@versilimidude2)

Use Pathlib

---

examples/sugarscape_g1mt/run.py
examples/sugarscape_g1mt/sugarscape_g1mt/model.py
examples/sugarscape_g1mt/sugarscape_g1mt/trader_agents.py

- update maybe_sell_spice() so calculate_MRS() takes potential sugar and spice based on trade
- update calculate_MRS() with kwargs so it can take potential trade but defaults to agents sugar and spice 
Update increases agent_reporter due to number of trades creating memory issues
- Update data collection so non-relevant data rmeoved on each step (i.e. sugar and spice agents don't have trade partners)

Fix bug in tutorial to calculate MRS with potential trade

---

examples/boid_flockers/boid_flockers/model.py
pyproject.toml
setup.cfg

Only `boltzmann_wealth_model` is enabled right now.
To use this, install the package, and do
```python
from mesa_models.boltzmann_wealth_model import model
model.compute_gini
```

feat: Create mesa-models as a package

---

examples/boltzmann_wealth_model/app.py
examples/conways_game_of_life/Readme.md
examples/conways_game_of_life/app.py

Streamlit browser app interface for Connway's game of life from the mesa example. Run the example using - streamlit run app.py. The animated grid is modelled using pandas and Altair.

Conways Game of life

---

examples/epstein_civil_violence/epstein_civil_violence/agent.py
examples/epstein_civil_violence/epstein_civil_violence/model.py
examples/epstein_civil_violence/epstein_civil_violence/server.py

This update changes a small set of bugs that was causing the model to not exhibit the cyclical explosions of active agents seen in the original Epstein paper. It also adds some small functionality to the browser display, introducing sliders to allow the user to change model parameters on the fly, and watch a graph of agent state numbers.
Bug Fixes
- Fix agent state logic
- Fix Moore vs Von Neuman neighborhood selection to use Epstein paper behavior
- Fix agent vision bug (was 1 and not parameter `vision` when calculating neighborhood, which also fixes agent movement issue)
- Fix arrestee state issue (arrestee was not being reset to "Quiescent", and so was counting as "Active" for all nearby agents)
Additions and Changes
- add model attributes to count agents and display a graph of agent …

Bug fixes and additions to Epstein Civil Violence

---

experimental/jupyter_viz.py

This is necessary to draw multiple "layers" for the trading Sugarscape. I will open the PR that implements Jupyter viz for trading Sugarscape after this one has been merged.

jupyter viz: Allow for custom space drawer

---

examples/epstein_civil_violence/epstein_civil_violence/model.py

The example is missing the `count_cops` abstract method in the file `examples/epstein_civil_violence/epstein_civil_violence/model.py`.
The model execution was failing due to the method not being implemented. Now is working

bugfix: Added count_cops method to the model

---

examples/virus_on_network/app.py

Waiting until https://github.com/projectmesa/mesa/pull/1767 is merged and we have a release.

solara: Add virus_on_network network example

---

gis/agents_and_networks/requirements.txt
gis/geo_schelling/requirements.txt
gis/geo_schelling_points/requirements.txt
gis/geo_sir/requirements.txt
gis/population/requirements.txt
gis/rainfall/requirements.txt
gis/urban_growth/requirements.txt

Update example dependency to mesa-geo v0.6.0. Closes #59.
Ready to merge once `mesa-viz-tornado` has a bug fix release (see https://github.com/projectmesa/mesa-viz-tornado/pull/37#issuecomment-1764013166).

gis: update gis examples to use mesa-geo v0.6.0

---

examples/sugarscape_g1mt/sugarscape_g1mt/model.py
examples/sugarscape_g1mt/sugarscape_g1mt/resource_agents.py
examples/sugarscape_g1mt/sugarscape_g1mt/trader_agents.py

This combines the Sugar and Spice resources into 1 resource class.
Rational:
- More concise code, which then requires less explanation
- Scales better with increasing number of resource types: see https://github.com/projectmesa/mesa/issues/1889#issuecomment-1827777988.

refactor: Simplify Sugarscape resource agents

---

examples/forest_fire/requirements.txt

This fixes forrest fire example from the 2.0 update, which is here: https://github.com/projectmesa/mesa-examples/pull/40
There are more that need to fixed. I will file a separate ticket for that. 
This is a small update and should resolve the one issue in #1922

Fix forest fire to update requirements to mesa 2.0.

---

examples/bank_reserves/bank_reserves/agents.py
examples/bank_reserves/bank_reserves/model.py
examples/bank_reserves/bank_reserves/server.py
examples/charts/charts/agents.py
examples/charts/charts/model.py
examples/epstein_civil_violence/epstein_civil_violence/model.py
examples/hex_snowflake/hex_snowflake/model.py
examples/sugarscape_cg/sugarscape_cg/model.py
examples/sugarscape_g1mt/sugarscape_g1mt/model.py
examples/wolf_sheep/wolf_sheep/server.py
examples/wolf_sheep/wolf_sheep/test_random_walk.py
gis/agents_and_networks/src/visualization/server.py
test_examples.py

Added a test that initiales and runs each model for 10 steps. Currently only handles core examples, not geo examples. 
To make the test file run I had to modify some imports to be relative imports.
Otherwise this PR fixes 1 error and 1 warning:
In the epstein_civil_violence model the `count_cops` method was missing
The hexgrid examples used `HexGrid`, which is deprecated and should be changed to `HexGridSingle`.

Test examples

---

gis/agents_and_networks/requirements.txt
gis/geo_schelling/requirements.txt
gis/geo_schelling_points/requirements.txt
gis/geo_sir/model.py
gis/geo_sir/requirements.txt
gis/population/requirements.txt
gis/rainfall/requirements.txt
gis/urban_growth/requirements.txt

- Update dependency to mesa-geo v0.7
- Spatial indexing is now taken care of in https://github.com/projectmesa/mesa-geo/pull/179. So it's not necessary to explicitly rebuild rtree index in the `geo_sir` example.

gis: update examples for mesa-geo v0.7.0

---

.github/workflows/build_lint.yml

Two modifications to the CI:
- Also test against mesa `main` branch. If any any model is updated, it should both the latest stable release and the main branch (or at least we should know if and why it fails).
- Run once a week (Monday 06:00 UTC) to test changing dependencies.
Closes #85.

CI: Test against mesa main, run weekly

---

examples/sugarscape_g1mt/sugarscape_g1mt/model.py

fix: Ensure schedule.steps is always incremented before data collection

---

examples/sugarscape_g1mt/sugarscape_g1mt/model.py

Depends on https://github.com/projectmesa/mesa/pull/1942 to be merged.

sugarscape_g1mt: Remove dependence on model.schedule.steps

---

examples/sugarscape_g1mt/sugarscape_g1mt/server.py

- During the refactor #71, the server.py wasn't properly ported to using `Resource`.

fix: Use resource agent for Sugarscape G1MT server.py

---

examples/virus_on_network/README.md
examples/virus_on_network/app.py
examples/virus_on_network/virus_on_network/model.py
examples/virus_on_network/virus_on_network/server.py

Change 1: Make the ReadMe more descriptive
1. Added a more detailed explanation of the model
2. Added an extra method of running the model
Change 2: Doc Strings and Cleaning
Made small changes to make the code more readable and easy to understand at first glance
NOTE: In the model, after running, some of the nodes in the graph are isolated. In my opinion it should be connected (if it was intentional then fine but in case not it needs to be updated with a different graph creation technique)

Improve Virus on Network documentation

---

examples/boid_flockers/boid_flockers/model.py

Changes Made:
1. Benchmark: Changed the default values and code to that of [benchmark](https://github.com/coderbeta1/mesa_copy/blob/main/benchmarks/Flocking/flocking.py)

Improve Boid Flocking model to benchmark

---

setup.cfg

This is needed so that
https://github.com/projectmesa/mesa-examples/pull/106 can inherit from sugarscape_cg, to reduce code duplication.

Publish sugarscape_cg to mesa_models

---

.github/workflows/build_lint.yml

Add a job to the Mesa-examples CI configuration to explicitly test against Mesa pre-releases. This could help detect regressions between the stable release and latest pre-release, or between the latest pre-release and main branch.
It basically narrows the search range if one of jobs fail.

CI: Add job to test against Mesa pre-releases

---

examples/boid_flockers/app.py
examples/boltzmann_wealth_model_experimental/app.py
examples/hotelling_law/app.py
examples/schelling_experimental/app.py
examples/sugarscape_g1mt/app.py
examples/virus_on_network/app.py

This updates all the examples to use the renamed and stabilized SolaraViz.
For reference:
- https://github.com/projectmesa/mesa/pull/2090
- https://github.com/projectmesa/mesa/pull/2188

Use SolaraViz instead of JupyterViz in examples

---

examples/bank_reserves/bank_reserves/agents.py
examples/bank_reserves/bank_reserves/model.py
examples/bank_reserves/batch_run.py
examples/boid_flockers/Flocker Test.ipynb
examples/boid_flockers/boid_flockers/SimpleContinuousModule.py
examples/boid_flockers/boid_flockers/model.py
examples/boltzmann_wealth_model/boltzmann_wealth_model/model.py
examples/boltzmann_wealth_model_experimental/model.py
examples/boltzmann_wealth_model_network/boltzmann_wealth_model_network/model.py
examples/caching_and_replay/model.py
examples/charts/charts/agents.py
examples/charts/charts/model.py
examples/color_patches/color_patches/model.py
examples/conways_game_of_life/conways_game_of_life/cell.py
examples/conways_game_of_life/conways_game_of_life/model.py
examples/el_farol/el_farol/agents.py
examples/el_farol/el_farol/model.py
examples/epstein_civil_violence/epstein_civil_violence/model.py
examples/forest_fire/Forest Fire Model.ipynb
examples/forest_fire/forest_fire/model.py
examples/hex_snowflake/hex_snowflake/cell.py
examples/hex_snowflake/hex_snowflake/model.py
examples/hotelling_law/app.py
examples/hotelling_law/hotelling_law/agents.py
examples/hotelling_law/hotelling_law/model.py
examples/schelling/model.py
examples/shape_example/shape_example/model.py
examples/virus_on_network/virus_on_network/model.py

This commit reverts PR #161 
- https://github.com/projectmesa/mesa-examples/pull/161
That PR assumed that time advancement would be done automatically, like proposed in https://github.com/projectmesa/mesa/pull/2223
We encountered some underlying issues with time, which we couldn't resolve in time.
So this PR reverts #161 fully and puts the schedulers back in place.

Revert PR #161: Replace schedulers with AgentSet functionality

---

.github/workflows/test_examples.yml
.github/workflows/test_gis_examples.yml
gis/agents_and_networks/src/agent/commuter.py
gis/agents_and_networks/src/model/model.py
gis/agents_and_networks/src/space/campus.py
gis/agents_and_networks/src/space/road_network.py
gis/agents_and_networks/src/visualization/server.py
gis/geo_sir/model.py
pyproject.toml
test_gis_examples.py

An effort to test all GIS models in CI.
PR is ready for review, all the CI and test code works as intended.
Some model example tests fail, and I will fix the most obvious ones, but all others can be fixed in separate PRs.

Make GIS models testable and test in CI

---

gis/geo_schelling/model.py
gis/geo_schelling_points/geo_schelling_points/model.py
gis/geo_sir/model.py
gis/population/population/model.py
gis/population/population/space.py
gis/rainfall/rainfall/model.py
gis/rainfall/rainfall/space.py
gis/urban_growth/urban_growth/model.py
gis/urban_growth/urban_growth/space.py

This PR addresses several of the remaining issues across the GIS examples:
- Corrects data file paths in the population, rainfall, and urban growth models to use relative paths from the script directory.
- Fixes the urban growth model by passing the model object to City and UrbanCell classes, as required by mesa-geo 0.8.0.
- Updates the population model to pass the model object when creating agents, ensuring they can access Model variables and properties.
- Corrects the use of `/vsigzip/` paths for GDAL compatibility.
The `/vsigzip/` situation is super weird. It isn't part of the file path, but it's a "marker" a GDAL convention. See https://github.com/projectmesa/mesa-geo/issues/235 for more details. 
Part of #172.

Fix data paths and model passing in GIS examples

---

examples/wolf_sheep/wolf_sheep/model.py

the datacollector allways includes grasspatches even if grass is False. This is breaking (the proposed changes to agent storage in Model)[https://github.com/projectmesa/mesa/pull/2251#issue-2488519860].
The underlying problem is that `Model.get_agents_of_type` now raises a `KeyError` if type does not exist. I think this is desirable behavior becuase errrors should not be passed over in silence. But this requires fixing the wolf sheep example as done here.

Ensure grasspatches info is only collected if gras is true

---

examples/schelling_experimental/model.py

Remove the remove temporary _advance_time() method from schelling_experimental. This isn't needed anymore, because in Mesa 3.0 time will be automatically increased.
See https://github.com/projectmesa/mesa/pull/2223.

schelling_experimental: Remove temporary _advance_time() method

---

.github/workflows/test_examples.yml
README.md
examples/conways_game_of_life_fast/Readme.md
examples/conways_game_of_life_fast/app.py
examples/conways_game_of_life_fast/model.py
pyproject.toml

This pull request adds a fast implementation of Conway's Game of Life using the `PropertyLayer`. Unlike traditional approaches, this version doesn't rely on a grid or agents, making it simpler and more efficient (in this specific case).
- The model uses a `PropertyLayer` to track cell states, removing the need for a grid or agents. In this layer, a cell value of 1 means being alive, and 0 means being dead.
- Neighbor counts are calculated using 2D convolution, which speeds up the process of applying the Game of Life rules.
- The model wraps the grid edges to create a continuous surface, so cells on the edges behave as if the grid is infinite.
- The model tracks and records the number of living cells and the percentage of the grid that's alive over time.
As benchmarked in …

Add fast PropertyLayer implementation of Game of Life

---

examples/bank_reserves/bank_reserves/agents.py
examples/bank_reserves/bank_reserves/model.py
examples/bank_reserves/batch_run.py
examples/boid_flockers/Flocker Test.ipynb
examples/boid_flockers/boid_flockers/SimpleContinuousModule.py
examples/boid_flockers/boid_flockers/model.py
examples/boltzmann_wealth_model/boltzmann_wealth_model/model.py
examples/boltzmann_wealth_model_experimental/model.py
examples/boltzmann_wealth_model_network/boltzmann_wealth_model_network/model.py
examples/caching_and_replay/model.py
examples/charts/charts/agents.py
examples/charts/charts/model.py
examples/color_patches/color_patches/model.py
examples/conways_game_of_life/conways_game_of_life/cell.py
examples/conways_game_of_life/conways_game_of_life/model.py
examples/el_farol/el_farol/agents.py
examples/el_farol/el_farol/model.py
examples/epstein_civil_violence/epstein_civil_violence/model.py
examples/forest_fire/Forest Fire Model.ipynb
examples/forest_fire/forest_fire/model.py
examples/hex_snowflake/hex_snowflake/cell.py
examples/hex_snowflake/hex_snowflake/model.py
examples/hotelling_law/app.py
examples/hotelling_law/hotelling_law/agents.py
examples/hotelling_law/hotelling_law/model.py
examples/schelling/model.py
examples/shape_example/shape_example/model.py
examples/virus_on_network/virus_on_network/model.py
test_examples.py

This reinstates PR #161 after the previous revert in #170.
Now that https://github.com/projectmesa/mesa/pull/2223 is merged, these examples are fully functional again without schedulers.
Original description of #161 below.
<hr>
This PR replace all the `RandomActivation` and `SimultaneousActivation` schedulers used in the example models with AgentSet functionality. This simplifies models and allows for easier and more flexible modification of these models. It algins the examples with the current best practices in Mesa.
The RandomActivation schedulers were removed, and in the Model.step() function the schedule step was replaced with an AgentSet operation, like:
```diff
-        self.schedule.step()
+        self.agents.shuffle().do("step")
```
The following RandomActivation schedulers were …

Reinstate PR #161: Replace schedulers with AgentSet functionality

---

gis/population/population/space.py
gis/rainfall/rainfall/space.py
gis/urban_growth/urban_growth/space.py

Use pass the new `rio_opener` argument with `gzip.open` in `RasterLayer.from_file()`. This prevents having to do the weird `/vsigzip/` stuff.
Note that urban_growth uses the rasterio opener directly, while the other two examples pass it via the mesa_geo.raster_layers.RasterLayer.open_file() method.
- Follow up on https://github.com/projectmesa/mesa-examples/pull/177
- Enabled by https://github.com/projectmesa/mesa-geo/pull/237
- Part of https://github.com/projectmesa/mesa-geo/issues/235
- Part of https://github.com/projectmesa/mesa-examples/issues/172

gis: Use gzip.open opener in RasterLayer.from_file

---

gis/population/population/space.py
gis/rainfall/rainfall/space.py

Fixes the _population_ and _rainfall_ models by passing `model` to `RasterLayer.from_file()`. 
> The RasterLayer creates Cells, Cells inherit from Agents, Agents need model input, but RasterLayer doesn't have access to model.
This reduces the number of GIS models that error by two, with now only one warning and one error left.
- As described in https://github.com/projectmesa/mesa-geo/issues/236
- Enabled by https://github.com/projectmesa/mesa-geo/pull/240
- Part of https://github.com/projectmesa/mesa-examples/issues/172

gis: Pass `model` to `RasterLayer.from_file()`

---

gis/geo_schelling/model.py
gis/geo_schelling/server.py

As part of https://github.com/projectmesa/mesa-examples/issues/172.

gis: fix user warning when testing geo schelling example

---

examples/sugarscape_g1mt/sugarscape_g1mt/model.py
examples/wolf_sheep/wolf_sheep/model.py

This PR updates the examples now that this PR is merged:
- https://github.com/projectmesa/mesa/pull/2267
The Model method `get_agents_of_type()` is replaced by the `agents_by_type` property, which directly returns the dict.
Instead of using:
```Python
model.get_agents_of_type(Wolf)
```
You should now use:
```Python
model.agents_by_type[Wolf]
```

Replace `get_agents_of_type` method with `agents_by_type` property

---

examples/aco_tsp/aco_tsp/model.py

Updates the `aoc_tsp` example by replace scheduler with AgentSet functionality.
```diff
-        self.schedule.step()
+        self.agents.shuffle().do("step")
```
Also use the new, standardized order of count-do-collect.
See:
- #183
- https://github.com/projectmesa/mesa/pull/2223
CC @zjost

aoc_tsp: Replace scheduler with AgentSet functionality

---

examples/boltzmann_wealth_model_experimental/app.py

Update to showcase the use of the new solaraviz API.

update boltzmann-wealth update to use new solaraviz api

---

examples/aco_tsp/app.py
examples/boid_flockers/app.py
examples/boltzmann_wealth_model_experimental/app.py
examples/conways_game_of_life_fast/app.py
examples/hotelling_law/app.py
examples/schelling_experimental/app.py
examples/sugarscape_g1mt/app.py
examples/virus_on_network/app.py

WIP to update the models to use the new solaraviz API.
This helps me to write a migration guide for things I notice. So far it goes smoothly, but is a bit tedious

update examples to use new solara_viz

---

examples/aco_tsp/aco_tsp/model.py
examples/bank_reserves/bank_reserves/model.py
examples/bank_reserves/batch_run.py
examples/boid_flockers/boid_flockers/model.py
examples/boltzmann_wealth_model/boltzmann_wealth_model/model.py
examples/boltzmann_wealth_model_experimental/model.py
examples/boltzmann_wealth_model_network/boltzmann_wealth_model_network/model.py
examples/caching_and_replay/model.py
examples/charts/charts/model.py
examples/el_farol/el_farol/model.py
examples/epstein_civil_violence/epstein_civil_violence/model.py
examples/forest_fire/Forest Fire Model.ipynb
examples/forest_fire/forest_fire/model.py
examples/hotelling_law/hotelling_law/model.py
examples/schelling/model.py
examples/schelling_experimental/model.py
examples/shape_example/shape_example/model.py
examples/virus_on_network/virus_on_network/model.py

Replace `shuffle().do()` in 18 models with the performance optimized `shuffle_do()` method.
`shuffle_do()` was added in https://github.com/projectmesa/mesa/pull/2283 and is first included in the upcoming Mesa `3.0.0a5` release. It allows for a drop-in performance upgrade:
```diff
- self.agents.shuffle().do("step")
+ self.agents.shuffle_do("step")
```
Which can speed up the Agent activation by over 3x depending on the scenario.
| Configuration                | shuffle().do() | shuffle(inplace=True).do() | shuffle_do() |
|------------------------------|----------------|----------------------------|--------------|
| 10,000 agents, 1,000 steps   | 8.27 s         | 3.65 s                     | 3.06 s       |
| 100,000 agents, 100 steps    | 13.71 s        | 6.31 s                     | 3.71 s …

Use performance optimized shuffle_do() method

---

examples/pd_grid/analysis.ipynb
examples/pd_grid/pd_grid/agent.py
examples/pd_grid/pd_grid/model.py
examples/pd_grid/pd_grid/server.py
examples/pd_grid/readme.md
examples/schelling/analysis.ipynb
examples/schelling_experimental/analysis.ipynb
examples/sugarscape_cg/Readme.md
examples/sugarscape_cg/sugarscape_cg/agents.py
examples/sugarscape_cg/sugarscape_cg/model.py
examples/sugarscape_g1mt/tests.py
examples/wolf_sheep/wolf_sheep/test_random_walk.py

This PR completes the migration from schedulers to AgentSet functionality across the mesa-examples repository for all regular (non-`gis`/-`rl`) examples. Key changes include:
- Replaced `RandomActivation`, `SimultaneousActivation`, and `RandomActivationByType` schedulers with appropriate AgentSet methods
- Updated `Model.step()` implementations to use AgentSet activation
- Removed references to `schedule.steps`, `schedule.agents`, and `schedule.agents_by_type`
- Updated agent addition/removal logic to work with AgentSets
- Adjusted data collection and visualization code to use `Model.steps` and `Model.agents`
For more details on migrating from schedulers to AgentSets, see the [migration guide](https://mesa.readthedocs.io/en/latest/migration_guide.html#time-and-schedulers).

Replace the remaining schedulers with AgentSet functionality

---

gis/agents_and_networks/src/agent/building.py
gis/agents_and_networks/src/agent/commuter.py
gis/agents_and_networks/src/agent/geo_agents.py
gis/geo_schelling/model.py
gis/geo_schelling_points/geo_schelling_points/agents.py
gis/geo_schelling_points/geo_schelling_points/model.py
gis/geo_sir/agents.py
gis/population/population/model.py
gis/rainfall/rainfall/model.py

Remove the `unique_id` from Agent init in the GIS models. This is now handled automatically in Mesa 3.0 (https://github.com/projectmesa/mesa/pull/2260).
Follows https://github.com/projectmesa/mesa-examples/pull/194.

gis: Remove unique_id from Agent init

---

gis/agents_and_networks/src/model/model.py
gis/geo_schelling/model.py
gis/geo_schelling_points/geo_schelling_points/model.py
gis/geo_sir/model.py
gis/population/population/space.py
gis/rainfall/rainfall/model.py

Remove more unique_ids from the Agents init in the GIS models.
Follows after the https://github.com/projectmesa/mesa-geo/pull/248
Merging directly, review still appreciated! Please take special care if unique_id in `ac.from_file`, `ac.from_GeoDataFrame` and `.add_agents` are correctly replaced.

gis: Remove more unique_ids

---

gis/agents_and_networks/src/model/model.py
gis/geo_schelling/model.py
gis/geo_schelling_points/geo_schelling_points/model.py
gis/population/population/model.py
gis/rainfall/rainfall/model.py
gis/urban_growth/urban_growth/model.py

Replace the schedulers in the GIS models with AgentSet functionality.
Similar to #183 and #202.

gis: Replace schedulers with AgentSet functionality

---

gis/urban_growth/urban_growth/model.py

Resolves the warning that this model doesn't have a schedule, which is doesn't need anymore.
See https://github.com/projectmesa/mesa/pull/2327.

gis: Replace initialize_data_collector with direct DataCollector

---

gis/geo_sir/model.py

Replace BaseScheduler in the GeoSir gis model with AgentSet functionality, using `agents_by_type`, `shuffle_do()` and `do()`.
- Remove BaseScheduler initialization and usage
- Use automatic agent registration for PersonAgents
- Explicitly register NeighbourhoodAgents with the model
- Update step() method to use AgentSet methods for agent activation
- Maintain original activation order: PersonAgents (shuffled) then NeighbourhoodAgents
- Remove unnecessary scheduler.add() calls
Closes #209, follows up #207, motivated by https://github.com/projectmesa/mesa/pull/2306, similar to https://github.com/projectmesa/mesa-examples/pull/183 and https://github.com/projectmesa/mesa-examples/pull/202.
CC @glicerico.

gis/GeoSir: Replace BaseScheduler with AgentSet functionality

---

examples/schelling/model.py

1. Remove unused model attributes
2. Make `similar` calculation more natural language readable
With these changes and `shuffle_do`, the Schelling code in https://github.com/JuliaDynamics/ABMFrameworksComparison should go down from 44 to ~33, closer to Agents.jl's 28.

refactor: Simplify Schelling code 

---

examples/caching_and_replay/model.py
examples/charts/charts/model.py
examples/color_patches/color_patches/model.py
examples/forest_fire/forest_fire/model.py
examples/hex_snowflake/hex_snowflake/model.py
examples/hotelling_law/hotelling_law/model.py
examples/shape_example/shape_example/model.py

[#2479](https://github.com/projectmesa/mesa/pull/2479) results in user warnings if random is not passed explicitly in `DiscreteSpace`, `AgentSet`, and `CellCollection`. This fixes it for the examples that did not do this correctly.

updates examples to explicitly set ranom on new style grid spaces

---

gis/agents_and_networks/app.py
gis/agents_and_networks/requirements.txt
gis/geo_schelling/app.py
gis/geo_schelling/requirements.txt
gis/geo_schelling_points/app.py
gis/geo_schelling_points/requirements.txt
gis/geo_sir/app.py
gis/geo_sir/requirements.txt
gis/population/app.py
gis/population/requirements.txt
gis/rainfall/app.py
gis/rainfall/requirements.txt
gis/urban_growth/app.py
gis/urban_growth/requirements.txt

For all gis examples:
- use `make_geospace_component` instead of `make_geospace_leaflet` in SolaraViz
- update Mesa-Geo dependency to v0.9.0

gis: use make_geospace_component in SolaraViz

---

examples/hotelling_law/tests.py
examples/warehouse/app.py
examples/warehouse/model.py
gis/agents_and_networks/src/space/campus.py
gis/agents_and_networks/src/space/utils.py
gis/geo_schelling_points/geo_schelling_points/space.py
gis/rainfall/app.py
gis/urban_growth/app.py

fix warehouse import for mesa tests to faciliate Mesa tests passing
This violates 2 person review to facilitate release of Mesa 3.2.0;

Fix warehouse model 

---

.codespellignore
.pre-commit-config.yaml

Hi!
This PR syncs the pre-commit configuration from the main Mesa repo to the Mesa examples repo.
It adds the `.codespellignore` file as well, because pre-commit depends on it, and will fail (locally) if it's not present.
This PR links to issue [2782](https://github.com/projectmesa/mesa/issues/2782) but specifically targets the first item in the list in that issue, to keep the PRs small and organized.

Sync the pre-commit config with Mesa

---

examples/bank_reserves/Readme.md

update the instructions to run the simulation (using Solara) and the URL to open it (using the updated port no.) 
small patch to @dlovell's fix for the `bank_reserves` example: #267.

fix(example): update readme for bank_transfer example

---

examples/aco_tsp/aco_tsp/model.py
rl/wolf_sheep/model.py

When fixing Ruff findings a bug was introduces that made a couple of arguments required which is actually not needed/the case. This PR fixes the issue.

fix: fix non-required inputs to be truly not required
